# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcm', '0003_fix_plural_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='testruns', to='tcm.Project'),
            preserve_default=False,
        ),
    ]
