# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcm', '0004_add_project_FK_to_testrun'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'organisation')]),
        ),
    ]
