# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcm', '0005_add_uniquetogether_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscenarioattribute',
            name='value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testscenariotemplateattribute',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
